# Generated by Django 5.0.7 on 2024-07-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='surgery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
