# Generated by Django 5.0.7 on 2024-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0002_patient_allergies_patient_medication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='allergies',
            new_name='alergias',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medication_details',
            new_name='cirurgia',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contact',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='surgery',
            new_name='detalhes_medicação',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='nascimento',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medication',
        ),
        migrations.AddField(
            model_name='patient',
            name='medicação',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
    ]
