# Generated by Django 5.0.7 on 2024-07-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0003_rename_allergies_patient_alergias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='endereço',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='alergias',
            new_name='allergies',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contato',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nascimento',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medicação',
            new_name='medication',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='cirurgia',
            new_name='medication_details',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='detalhes_medicação',
            new_name='surgery',
        ),
    ]
