# Generated by Django 5.0.7 on 2024-07-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='protocol_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
