# Generated by Django 5.0.7 on 2024-07-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0006_appointment_protocol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
