# Generated by Django 5.0.7 on 2024-07-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0007_appointment_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled',
        ),
    ]
