# Generated by Django 5.0.7 on 2024-07-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0010_alert_billing_expense_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='protocol',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
