# Generated by Django 5.0.7 on 2024-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0011_appointment_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='protocol',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
    ]
