# Generated by Django 5.0.7 on 2024-07-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0012_remove_appointment_protocol_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('dentist', 'Dentista'), ('orthodontist', 'Ortodontista'), ('surgeon', 'Cirurgião'), ('other', 'Outro')], max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('hired_date', models.DateField()),
            ],
        ),
    ]
