# Generated by Django 5.0.7 on 2024-07-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0013_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
