# Generated by Django 5.0.7 on 2024-07-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0014_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('dentist', 'Dentista'), ('orthodontist', 'Ortodontista'), ('surgeon', 'Cirurgião'), ('other', 'Outro')], max_length=50)),
                ('contato', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField()),
                ('data_cadastro', models.DateField()),
                ('cro', models.CharField(max_length=20)),
            ],
        ),
    ]
