# Generated by Django 5.0.7 on 2024-07-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0015_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
    ]
