# Generated by Django 5.0.7 on 2024-07-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0017_doctor_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='ativo',
        ),
    ]
