# Generated by Django 5.0.7 on 2024-07-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_odonto', '0018_remove_doctor_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
